### PR TITLE
Advent Calendar Day.9 - IoT

### PR DESCRIPTION
**Pull request by yosi-q**
@eliotc1986 @imony 

Please review my article.

Thank you!

### CODE REVIEW

**Review by shin10kudev — CHANGES_REQUESTED** [review]
Please optimize your photos. I recommend using imageOptim or tinyPng

optimize

Also, please branch from dev using `article/name-of-article` format. 🙏 You don't need to fork project each time.

**Comment by yosi-q** [comment]
@eliotc1986 san

Thank you for the comment.
I used recommended tool and update my pics.

I'll make branch on this project from the next time.

Please confirm again!

Thank you

**Review by shin10kudev — APPROVED** [review]
LGTM!
Please merge when you are ready

**Comment by yosi-q** [comment]
@eliotc1986 san

Thanks for reviewing. I have just merged!

**Pull request merged**
