### PR TITLE
Create article - report of meetup 201903

### PR DESCRIPTION
**Pull request by yosi-q**
Hi @eliotc1986 san!

I wrote blog article which report of last meetup event.
Please have a look and let me know any problems.

Thank you!

### CODE REVIEW

**Comment by shin10kudev** [comment]
@yoshiqsato Thanks for waiting! I don't see any problems. I will do a local check, merge and deploy

**Review by shin10kudev — DISMISSED** [review]
LGTM

**Comment by shin10kudev** [comment]
@yosi-q I see that you don't have an image included in your post. Could you add an image file and add it to your .yml file in the contents section (e.g. `image: img/posts/electron-cover.jpg` )

**Comment by shin10kudev** [comment]
@yosi-q By the way, since you are a contributor to this project you don't need to create pull requests from a forked branch. I would prefer you work from the same source code, and check out branches from `dev` using this format: `article/name_of_your_article` or `feature/description_of_changes`.

Then you can just create a pull request for `dev` from that branch. It is simpler that way 😃

**Comment by yosi-q** [comment]
Hi @eliotc1986,

I added image and modified some changes regarding next meetup event.
Please review this PR.

I tried to push ``dev`` branch directly but got following error.
```
remote: error: GH006: Protected branch update failed for refs/heads/dev.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/yamagata-developers-society/blog.git
 ! [remote rejected] dev -> dev (protected branch hook declined)
error: failed to push some refs to 'https://github.com/yamagata-developers-society/blog.git'
```

Please let me know if you have any solution next time we meet...

Thank you,

**Comment by shin10kudev** [comment]
@yosi-q Thanks! 

Yes, dev branch is a protected branch, so could you try the following:

```
git checkout dev
git pull origin dev // ensure you have latest changes from dev
git checkout -b <name_of_your_branch>
// make changes
git push --set-upstream origin <name_of_your_branch>
```
From here create a merge request with your target set to `dev`

Does this make sense?

**Pull request closed without merging**
